#!/bin/bash
#Script to find error on Westpac EUID

echo "please insert EUID:"
read EUID1
echo "**************************************************************************************"
grep $EUID1 /var/lib/tsm/westpac-prod/tmpQuerySD/SUBSCRIBERS_2016* | sed 's/^.....................................//'| sed 's/..........................................................................................................................$//'
echo "**************************************************************************************"
echo "**************************************************************************************"
echo "Insert the latest querySD file name. SUBSCRIBERS_2016xxxx_xxxxxx.txt"
read SUBSFILE
grep $EUID1 /var/lib/tsm/westpac-prod/tmpScriptsToCps/out_$SUBSFILE
echo "**************************************************************************************"
echo " ** Noted:Invalid respond data negative or KO means negative respond from SKMS******"
echo " CPLC"
grep  $EUID1 /var/lib/tsm/westpac-prod/tmpQuerySD/SUBSCRIBERS_2016* | sed 's/^........................................................................................................//'| sed 's/..$//'
echo " CPLC to look in debug"
CPCL2=`grep  $EUID1 /var/lib/tsm/westpac-prod/tmpQuerySD/SUBSCRIBERS_2016* | sed 's/^........................................................................................................//'| sed 's/..................................................$//'`
echo $CPCL2
echo "copy the short CPLC"
read CPLC3
echo "looking on debug logs"
zgrep -B 20 $CPLC3 /var/container_data/westpac-prod/log/debug* | grep ID
echo "Copy path of the file"
read PATH1
echo "**********"
echo "Copy ID number"
read IDN1
zgrep -A 27 "ID: $IDN1 $PATH1
